#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill $SCRIPTPATH/background.jpg
fi

#boot picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom -b &> /dev/null & 
fi

# Give's notification when changing workspace
if pgrep wsnd; then
	killall -q wsnd
fi
~/.scripts/wsnd &

#security things
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=pkcs11 &

#some startup app
dunst &
nm-applet &
start-pulseaudio-x11 &

#XFCE Stuff
xfce4-power-manager &
#/usr/bin/xfsettingsd&
#xfce4-panel &> /dev/null &

#boot polybar based on the number of monitors found
if [ -x "$(command -v polybar)" ]; then
  pkill polybar
  index=0
  monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"

  leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
  do
    barname="mainbar$index"
    monitor=$monitor offsetx=$x width=$width polybar -c $SCRIPTPATH/polybar.conf $barname &> /dev/null &
    let index=index+1
  done
fi
