#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/down.jpg
fi

echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

pkill picom &
pkill nm-applet &
#pkill xfce4-panel &
pkill dunst &
pkill wsnd &
pkill polybar &
pkill xfce4-power-manager &
#pkill xfsettingsd &
